#page title
page_title                                : Paner                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1664769370                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ro                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
#playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Paner                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your grocery lists stored in one place and at the tip of your fingers. With financial and product charts automatically generated, grocery shopping sounds more fun.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Daniel Gogozan
your_link                                 : https://www.linkedin.com/in/daniel-gogozan-48a667209/
your_city                                 : Romania
email_address                             : gogozandaniel@gmail.com
#facebook_username                         :
instagram_username                        : danielgogozan
#twitter_username                          :
github_username                           : danielgogozan
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fast grocery list creation & planning
    description                           : Planning will help you reduce food waste, save time & money.
    fontawesome_icon_name                 : magic
    
  - title                                 : Shared lists
    description                           : Build grocery lists toghether with your family members or friends, in realtime, so that you are all in sync.
    fontawesome_icon_name                 : share

  - title                                 : Track financials
    description                           : The costs are converted into visual graphs for a better understanding of your consumer behavior.
    fontawesome_icon_name                 : chart-line

  - title                                 : Product categories distribution
    description                           : Identify the categories of products that are most relevant and frequent for you.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Informed by widgets
    description                           : Widgets are a great way to have lists always at hand for faster access.
    fontawesome_icon_name                 : bullseye

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ad6836"
cover_overlay_transparency                : 0.45

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#21412B"

link_color                                : "#3678f7"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#F4924A"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#F4924A"
feature_icons_background_color            : "#ffd3b3"

social_icons_foreground_color             : "#2E2E2B"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
